version: "2"

services:
  hardhat:
    build:
      context: ../hardhat-template
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - dockernet
    command: yarn run dev
    volumes:
      - ../hardhat-template:/app
      - /app/node_modules
      - ../contracts:/app/tmp/contracts
    ports:
      - "8545:8545"

#  ganache:
#    container_name: ganache
#    networks:
#      - dockernet
#    build:
#      context: ./ganache
#    ports:
#      - "8545:8545"
#      - "8546:8546"

  pg:
    image: postgres:13.0
    restart: always
    networks:
      - dockernet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=chainlink
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=500 -c shared_buffers=4GB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  chainlink:
    build: "chainlink"
    env_file:
      - chainlink.hardhat.env
    restart: always
    networks:
      - dockernet
    ports:
      - "5100:5100"
      - "6688:6688"
    links:
      - "hardhat"
#      - "ganache"
      - "pg"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - .:/host

networks:
  dockernet: